version: '3'

services:
  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    volumes:
      - ./jmeter-scripts:/tests
    working_dir: /tests
    command: -n -t test.jmx -l results.jtl
